import React from 'react';
export default function Workflows({data,act,busy}) {
 return <div className="enablement">
  <section className="panel"><h2>CRM operations → accounting review</h2><p>One run reads the workspace, prepares missing-document and overdue-invoice drafts, checks job budgets, and gathers payable and reconciliation exceptions. Staff retain control of approvals and sending.</p><p>This workflow uses validated rules. It does not invoke an AI model, send emails, post ledger entries or make payments.</p><form onSubmit={e=>{e.preventDefault();act('workflows/operations',Object.fromEntries(new FormData(e.currentTarget)),'Workflow completed — review the results below');}}><label className="field"><span>Run reference</span><input name="run_key" required minLength={3} maxLength={100} pattern="[A-Za-z0-9_:-]+" defaultValue={'operations:'+data.today} /></label><p>Reuse the same reference to retrieve the original result safely. Use a new reference after records change. Reminder drafts still have their own same-day duplicate protection.</p><button className="primary" disabled={busy}>{busy?'Running…':'Run operations workflow'}</button></form></section>
  <section className="panel"><h2>Where AI fits next</h2><p>The Knowledge desk supports an optional local-model draft from approved excerpts. For this operations workflow, the next AI extension is document extraction and email classification, followed by validated proposals for staff review. Neither extension is active here.</p><p>External orchestration can call this API. A local n8n workflow template is included in the repository; connecting an actual account and enabling a schedule are separate setup steps.</p></section>
  {data.workflow_runs.length===0&&<section className="panel"><p>No runs yet. Run the workflow to prepare drafts and collect review items.</p></section>}
  {data.workflow_runs.map(run=><section className="panel" key={run.id}><h2>{run.run_key}</h2><p>{new Date(run.created_at).toLocaleString()} · Snapshot at run time</p><ol>{run.result.steps.map(step=><li key={step.name}>{step.name} — <strong>{step.status}</strong></li>)}</ol><p><strong>{run.result.followups.created}</strong> drafts created · {run.result.followups.reused} existing drafts reused · 0 messages sent</p><div className="tablewrap"><table><thead><tr><th>Area</th><th>Record</th><th>Next action</th><th>Reason</th></tr></thead><tbody>{run.result.exceptions.map((x,i)=><tr key={i}><td>{x.area}</td><td>{x.record}</td><td>{x.action}</td><td>{x.reason}</td></tr>)}</tbody></table></div><p>Open the relevant workspace page to review and resolve these items. Run history preserves the original snapshot.</p></section>)}
 </div>;
}
