import React from 'react';
export default function Workflows({data,act,busy}) {
 return <div className="enablement">
  <section className="panel"><h2>CRM operations → accounting review</h2><p>One run reads the workspace, prepares missing-document and overdue-invoice drafts, checks job budgets, and gathers payable and reconciliation exceptions. Staff retain control of approvals and sending.</p><p>This workflow uses validated rules. It does not invoke an AI model, send emails, post ledger entries or make payments.</p><form onSubmit={e=>{e.preventDefault();act('workflows/operations',Object.fromEntries(new FormData(e.currentTarget)),'Workflow completed — review the results below');}}><label className="field"><span>Run reference</span><input name="run_key" required minLength={3} maxLength={100} pattern="[A-Za-z0-9_:-]+" defaultValue={'operations:'+data.today} /></label><p>Reuse the same reference to retrieve the original result safely. Use a new reference after records change. Reminder drafts still have their own same-day duplicate protection.</p><button className="primary" disabled={busy}>{busy?'Running…':'Run operations workflow'}</button></form></section>
  <section className="panel"><h2>1. Automated checks → 2. AI investigation → 3. Accountant review</h2><p>The AI can choose read-only tools to inspect clients, jobs, invoices and reconciliation records, then propose next steps with evidence references. It cannot send messages, change records or make payments.</p><p>{data.model_configured ? 'AI is connected. Investigations send workspace records to the configured model provider. Use sample data only; AI output requires review.' : 'AI investigation is not connected yet. The server needs a model connection to enable step 2. Automated checks remain available.'}</p><p>Accountant approval records a decision only; it does not execute external actions. Reviewer names are labels in this prototype, not authenticated identities.</p></section>
  {data.workflow_runs.length===0&&<section className="panel"><p>No runs yet. Run the workflow to prepare drafts and collect review items.</p></section>}
  {data.workflow_runs.map(run=><section className="panel" key={run.id}><h2>{run.run_key}</h2><p>{new Date(run.created_at).toLocaleString()} · Snapshot at run time</p><ol>{run.result.steps.map(step=><li key={step.name}>{step.name} — <strong>{step.status}</strong></li>)}</ol><p><strong>{run.result.followups.created}</strong> drafts created · {run.result.followups.reused} existing drafts reused · 0 messages sent</p><div className="tablewrap"><table><thead><tr><th>Area</th><th>Record</th><th>Next action</th><th>Reason</th></tr></thead><tbody>{run.result.exceptions.map((x,i)=><tr key={i}><td>{x.area}</td><td>{x.record}</td><td>{x.action}</td><td>{x.reason}</td></tr>)}</tbody></table></div><p>Open the relevant workspace page to review and resolve these items. Run history preserves the original snapshot.</p>
<button className="primary" disabled={busy || !data.model_configured} onClick={()=>act('workflows/'+run.id+'/investigate',{},'Investigation completed — review the AI proposal')}>Investigate with AI</button>
{data.agent_reviews.filter(r=>r.run_id===run.id).map(review=><div className="reviewbox" key={review.id}><h3>AI investigation · {review.status}</h3>{review.payload.error && <p>{review.payload.error}</p>}<p>{review.payload.summary}</p><ul>{(review.payload.recommendations||[]).map((r,i)=><li key={i}>{r}</li>)}</ul><p>Evidence: {(review.payload.evidence_ids||[]).join(', ')}</p><details><summary>Read-only investigation trace</summary><ul>{(review.payload.trace||[]).map((t,i)=><li key={i}>{t.tool}: {t.evidence_ids.join(', ')}</li>)}</ul></details>{review.status==='Awaiting review' && <form onSubmit={e=>{e.preventDefault();act('agent-reviews/'+review.id+'/decision',Object.fromEntries(new FormData(e.currentTarget)),'Review recorded; no external actions executed');}}><label className="field"><span>Reviewer label</span><input name="reviewer" required minLength={2} maxLength={100}/></label><label className="field"><span>Decision</span><select name="decision"><option>Rejected</option><option>Approved</option></select></label><label className="field"><span>Evidence checked and decision notes</span><textarea name="note" required minLength={10} maxLength={1000}/></label><button disabled={busy}>Record decision</button></form>}{review.decision.at&&<p>{review.decision.decision} by {review.decision.reviewer}: {review.decision.note}. No external action executed.</p>}</div>)}</section>)}
 </div>;
}
